/**
 * © Sobyte
 *
 * @author : Sobhan Bera (sobhanbera)
 * @other_editors :
 * @file : Typescript
 *
 * Purpose - variables, objects, constants, etc.
 */

import {GenreData} from '@/schemas'

export const AppSearchSuggestions: string[] = [
    'romantic tracks',
    'arijit singh',
    'jubin nautiyal',
    'bollywood hits',
    'hindi lo-fi',
    'hindi mashups',
]

/**
 * a list of genres to render on the screen
 * this contains some popular genre only
 * there are many other genre/sub-genre too..
 */
export const GenreList: Array<GenreData> = [
    {
        id: 0,
        title: 'Pop',
        artwork: '',
        hqArtwork: '',
        color: '#203870',
        searchQuery: '',
    },
    {
        id: 1,
        title: 'Rock',
        artwork: '',
        hqArtwork: '',
        color: '#2E6171',
        searchQuery: '',
    },
    {
        id: 2,
        title: 'Hip Hop',
        artwork: '',
        hqArtwork: '',
        color: '#F4442E',
        searchQuery: '',
    },
    {
        id: 3,
        title: 'EDM',
        artwork: '',
        hqArtwork: '',
        color: '#726E97',
        searchQuery: '',
    },
    {
        id: 4,
        title: 'R&B',
        artwork: '',
        hqArtwork: '',
        color: '#A01800',
        searchQuery: '',
    },
    {
        id: 5,
        title: 'Country',
        artwork: '',
        hqArtwork: '',
        color: '#02394A',
        searchQuery: '',
    },
    {
        id: 6,
        title: 'Folk',
        artwork: '',
        hqArtwork: '',
        color: '#006494',
        searchQuery: '',
    },
    {
        id: 7,
        title: 'Classical',
        artwork: '',
        hqArtwork: '',
        color: '#0C73EC',
        searchQuery: '',
    },
    {
        id: 8,
        title: 'Romance',
        artwork: '',
        hqArtwork: '',
        color: '#EB4B98',
        searchQuery: '',
    },
    {
        id: 9,
        title: 'K-Pop',
        artwork: '',
        hqArtwork: '',
        color: '#B95D06',
        searchQuery: '',
    },
    {
        id: 10,
        title: 'Metal',
        artwork: '',
        hqArtwork: '',
        color: '#604D53',
        searchQuery: '',
    },
    {
        id: 11,
        title: 'Jazz',
        artwork: '',
        hqArtwork: '',
        color: '#5AA0F6',
        searchQuery: '',
    },
    {
        id: 12,
        title: 'World',
        artwork: '',
        hqArtwork: '',
        color: '#483868',
        searchQuery: '',
    },
    {
        id: 13,
        title: 'Latin',
        artwork: '',
        hqArtwork: '',
        color: '#CC2936',
        searchQuery: '',
    },
    {
        id: 14,
        title: 'Dance',
        artwork: '',
        hqArtwork: '',
        color: '#284878',
        searchQuery: '',
    },
    {
        id: 15,
        title: 'Orchestra',
        artwork: '',
        hqArtwork: '',
        color: '#E8B848',
        searchQuery: '',
    },
    {
        id: 16,
        title: 'Indie',
        artwork: '',
        hqArtwork: '',
        color: '#582820',
        searchQuery: '',
    },
    {
        id: 17,
        title: 'Soul',
        artwork: '',
        hqArtwork: '',
        color: '#0B3948',
        searchQuery: '',
    },
    {
        id: 18,
        title: 'Blues',
        artwork: '',
        hqArtwork: '',
        color: '#385080',
        searchQuery: '',
    },
]

/**
 * this is the language data list
 * and also contains data about different music industries
 */
export const LanguagesList: Array<GenreData> = [
    {
        id: 0,
        title: 'Bollywood',
        artwork: '',
        hqArtwork: '',
        color: '#BFA128',
        searchQuery: '',
    },
    {
        id: 1,
        title: 'Hindi',
        artwork: '',
        hqArtwork: '',
        color: '#FA5844',
        searchQuery: '',
    },
    {
        id: 2,
        title: 'Punjabi',
        artwork: '',
        hqArtwork: '',
        color: '#72D6BE',
        searchQuery: '',
    },
    {
        id: 3,
        title: 'Bengali',
        artwork: '',
        hqArtwork: '',
        color: '#3888A0',
        searchQuery: '',
    },
    {
        id: 4,
        title: 'Bollywood Retro',
        artwork: '',
        hqArtwork: '',
        color: '#F85A28',
        searchQuery: '',
    },
    {
        id: 5,
        title: 'Tamil',
        artwork: '',
        hqArtwork: '',
        color: '#F59B23',
        searchQuery: '',
    },
    {
        id: 6,
        title: 'Telugu',
        artwork: '',
        hqArtwork: '',
        color: '#5AA0F6',
        searchQuery: '',
    },
    {
        id: 7,
        title: 'Marathi',
        artwork: '',
        hqArtwork: '',
        color: '#0C73EC',
        searchQuery: '',
    },
    {
        id: 8,
        title: 'Gujrati',
        artwork: '',
        hqArtwork: '',
        color: '#8C67AC',
        searchQuery: '',
    },
    {
        id: 9,
        title: 'Kannada',
        artwork: '',
        hqArtwork: '',
        color: '#A83000',
        searchQuery: '',
    },
    {
        id: 10,
        title: 'Haryanvi',
        artwork: '',
        hqArtwork: '',
        color: '#681038',
        searchQuery: '',
    },
    {
        id: 11,
        title: 'Malayalam',
        artwork: '',
        hqArtwork: '',
        color: '#206870',
        searchQuery: '',
    },
]

/**
 * list providing data about mood of the track/songs
 */
export const MoodsList: Array<GenreData> = [
    {
        id: 0,
        title: 'Romance',
        artwork: '',
        hqArtwork: '',
        color: '#EB4B98',
        searchQuery: '',
    },
    {
        id: 1,
        title: 'Happy',
        artwork: '',
        hqArtwork: '',
        color: '#1E3264',
        searchQuery: '',
    },
    {
        id: 2,
        title: 'Energetic',
        artwork: '',
        hqArtwork: '',
        color: '#5AA0F6',
        searchQuery: '',
    },
    {
        id: 3,
        title: 'Sad',
        artwork: '',
        hqArtwork: '',
        color: '#784840',
        searchQuery: '',
    },
    {
        id: 4,
        title: 'Calm',
        artwork: '',
        hqArtwork: '',
        color: '#A04008',
        searchQuery: '',
    },
    {
        id: 5,
        title: 'Relax',
        artwork: '',
        hqArtwork: '',
        color: '#25302A',
        searchQuery: '',
    },
    {
        id: 6,
        title: 'Dark',
        artwork: '',
        hqArtwork: '',
        color: '#0C73EC',
        searchQuery: '',
    },
    {
        id: 7,
        title: 'Lo-Fi',
        artwork: '',
        hqArtwork: '',
        color: '#5AA0F6',
        searchQuery: '',
    },
    {
        id: 8,
        title: 'Devotional',
        artwork: '',
        hqArtwork: '',
        color: '#7D161A',
        searchQuery: '',
    },
]

/**
 * different time and situation when the user could listen to songs
 * time/scene of the track...
 */
export const MusicTimesList: Array<GenreData> = [
    {
        id: 0,
        title: 'Party',
        artwork: '',
        hqArtwork: '',
        color: '#0C73EC',
        searchQuery: '',
    },
    {
        id: 1,
        title: 'Sleep',
        artwork: '',
        hqArtwork: '',
        color: '#F59B23',
        searchQuery: '',
    },
    {
        id: 2,
        title: 'Workout',
        artwork: '',
        hqArtwork: '',
        color: '#1E3264',
        searchQuery: '',
    },
    {
        id: 3,
        title: 'Drive',
        artwork: '',
        hqArtwork: '',
        color: '#8C67AC',
        searchQuery: '',
    },
    {
        id: 4,
        title: 'Study',
        artwork: '',
        hqArtwork: '',
        color: '#2D46BA',
        searchQuery: '',
    },
    {
        id: 5,
        title: 'Morning',
        artwork: '',
        hqArtwork: '',
        color: '#477D95',
        searchQuery: '',
    },
    {
        id: 6,
        title: 'Friends',
        artwork: '',
        hqArtwork: '',
        color: '#E8125C',
        searchQuery: '',
    },
    {
        id: 7,
        title: 'Alone',
        artwork: '',
        hqArtwork: '',
        color: '#B95D06',
        searchQuery: '',
    },
    {
        id: 8,
        title: 'Gaming',
        artwork: '',
        hqArtwork: '',
        color: '#5AA0F6',
        searchQuery: '',
    },
]

export const ExtraMusicTypesList: Array<GenreData> = [
    {
        id: 0,
        title: 'New Releases',
        artwork: '',
        hqArtwork: '',
        color: '#1E3264',
        searchQuery: '',
    },
    {
        id: 1,
        title: 'Eng x Hind',
        artwork: '',
        hqArtwork: '',
        color: '#8B9A46',
        searchQuery: '',
    },
    {
        id: 2,
        title: 'Travel',
        artwork: '',
        hqArtwork: '',
        color: '#C84B31',
        searchQuery: '',
    },
    {
        id: 4,
        title: 'Focus',
        artwork: '',
        hqArtwork: '',
        color: '#2CA3B8',
        searchQuery: '',
    },
    {
        id: 5,
        title: 'Ambient',
        artwork: '',
        hqArtwork: '',
        color: '#09578F',
        searchQuery: '',
    },
    {
        id: 6,
        title: 'Instrumental',
        artwork: '',
        hqArtwork: '',
        color: '#E9724C',
        searchQuery: '',
    },
    {
        id: 7,
        title: 'Holidays',
        artwork: '',
        hqArtwork: '',
        color: '#712B75',
        searchQuery: '',
    },
    {
        id: 8,
        title: '90s Times',
        artwork: '',
        hqArtwork: '',
        color: '#0C73EC',
        searchQuery: '',
    },
    {
        id: 9,
        title: '80s Times',
        artwork: '',
        hqArtwork: '',
        color: '#7D161A',
        searchQuery: '',
    },
    {
        id: 10,
        title: "Feelin' Good",
        artwork: '',
        hqArtwork: '',
        color: '#C5283D',
        searchQuery: '',
    },
    {
        id: 11,
        title: 'Kids',
        artwork: '',
        hqArtwork: '',
        color: '#606D5D',
        searchQuery: '',
    },
    {
        id: 12,
        title: 'Good Vibes',
        artwork: '',
        hqArtwork: '',
        color: '#255F85',
        searchQuery: '',
    },
    {
        id: 13,
        title: 'Slowed + Reverbed',
        artwork: '',
        hqArtwork: '',
        color: '#B85C38',
        searchQuery: '',
    },
    {
        id: 14,
        title: 'Folk',
        artwork: '',
        hqArtwork: '',
        color: '#6E85B7',
        searchQuery: '',
    },
    {
        id: 15,
        title: 'Indian Classical',
        artwork: '',
        hqArtwork: '',
        color: '#FF9933',
        searchQuery: '',
    },
    {
        id: 16,
        title: 'DJs',
        artwork: '',
        hqArtwork: '',
        color: '#F37878',
        searchQuery: '',
    },
    {
        id: 17,
        title: 'Remix',
        artwork: '',
        hqArtwork: '',
        color: '#516BEB',
        searchQuery: '',
    },
    {
        id: 18,
        title: 'Mixtape',
        artwork: '',
        hqArtwork: '',
        color: '#354259',
        searchQuery: '',
    },
    {
        id: 19,
        title: 'Chill',
        artwork: '',
        hqArtwork: '',
        color: '#748DA6',
        searchQuery: '',
    },
    {
        id: 20,
        title: 'Top Hits',
        artwork: '',
        hqArtwork: '',
        color: '#65C18C',
        searchQuery: '',
    },
    {
        id: 21,
        title: 'Remakes',
        artwork: '',
        hqArtwork: '',
        color: '#5E454B',
        searchQuery: '',
    },
    {
        id: 22,
        title: 'T-Series',
        artwork: '',
        hqArtwork: '',
        color: '#4C4C6D',
        searchQuery: '',
    },
    {
        id: 23,
        title: 'Today',
        artwork: '',
        hqArtwork: '',
        color: '#1C6DD0',
        searchQuery: '',
    },
    {
        id: 23,
        title: 'Mashups',
        artwork: '',
        hqArtwork: '',
        color: '#3797A4',
        searchQuery: '',
    },
    {
        id: 24,
        title: 'Random',
        artwork: '',
        hqArtwork: '',
        color: '#7868E6',
        searchQuery: '',
    },
]
