/**
 * © Sobyte
 *
 * @author : Sobhan Bera (sobhanbera)
 * @other_editors :
 * @file : Typescript
 *
 * Purpose - variables, objects, constants, etc.
 */

import {GenreData} from '@/schemas'

/**
 * a list of genres to render on the screen
 * this contains some popular genre only
 * there are many other genre/sub-genre too..
 */
export const GenreList: Array<GenreData> = [
    {
        id: 0,
        title: 'Pop',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 1,
        title: 'Rock',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 2,
        title: 'Hip Hop',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 3,
        title: 'EDM',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 4,
        title: 'R&B',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 5,
        title: 'Country',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 6,
        title: 'Folk',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 7,
        title: 'Classical',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 8,
        title: 'Romance',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 9,
        title: 'K-Pop',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 10,
        title: 'Metal',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 11,
        title: 'Jazz',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 12,
        title: 'World',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 13,
        title: 'Latin',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 14,
        title: 'Dance',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 15,
        title: 'Orchestra',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 16,
        title: 'Indie',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 17,
        title: 'Soul',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 18,
        title: 'Blues',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
]

/**
 * this is the language data list
 * and also contains data about different music industries
 */
export const LanguagesList: Array<GenreData> = [
    {
        id: 0,
        title: 'Bollywood',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 1,
        title: 'Hindi',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 2,
        title: 'Punjabi',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 3,
        title: 'Bengali',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 4,
        title: 'Bollywood Retro',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 5,
        title: 'Tamil',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 6,
        title: 'Telugu',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 7,
        title: 'Marathi',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 8,
        title: 'Gujrati',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 9,
        title: 'Kannada',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 10,
        title: 'Haryanvi',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 11,
        title: 'Malayalam',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
]

/**
 * list providing data about mood of the track/songs
 */
export const MoodsList: Array<GenreData> = [
    {
        id: 0,
        title: 'Romance',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 1,
        title: 'Happy',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 2,
        title: 'Energetic',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 3,
        title: 'Sad',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 4,
        title: 'Calm',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 5,
        title: 'Relax',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 6,
        title: 'Lo-Fi',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 7,
        title: 'Lo-Fi',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 8,
        title: 'Devotional',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
]

/**
 * different time and situation when the user could listen to songs
 * time/scene of the track...
 */
export const MusicTimesList: Array<GenreData> = [
    {
        id: 0,
        title: 'Party',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 1,
        title: 'Sleep',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 2,
        title: 'Workout',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 3,
        title: 'Drive',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 4,
        title: 'Study',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 5,
        title: 'Morning',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 6,
        title: 'Friends',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 7,
        title: 'Alone',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 8,
        title: 'Gaming',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
]

export const ExtraMusicTypesList: Array<GenreData> = [
    {
        id: 0,
        title: 'New Releases',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 1,
        title: 'Summer',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 2,
        title: 'Travel',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 3,
        title: 'Netflix',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 4,
        title: 'Focus',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 5,
        title: 'Kids',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 6,
        title: 'Instrumental',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 7,
        title: 'Holidays',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 8,
        title: '90s',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 9,
        title: '80s',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 10,
        title: "Feelin' Good",
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 11,
        title: 'Ambient',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 12,
        title: 'Good Vibes',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
    {
        id: 13,
        title: 'Slowed + Reverbed',
        artwork: '',
        hqArtwork: '',
        color: '',
        searchQuery: '',
    },
]
